# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('days_left', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sam_account_name', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200, null=True)),
                ('is_manager', models.NullBooleanField()),
                ('photo_number', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoNumberRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sam_account_name', models.CharField(max_length=200, unique=True)),
                ('photo_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='leave',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
