# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='display_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_manager',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sam_account_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
