# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20170415_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='person_id',
            new_name='person',
        ),
    ]
