# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20170415_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='sam_account_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
