# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20170422_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo_number',
            field=models.IntegerField(null=True),
        ),
    ]
