# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20170416_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='sam_account_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
